apiVersion: v1
kind: Secret
metadata:
  name: financial-hub-secret
type: Opaque
stringData:
  DB_USER: financial
  DB_PASSWORD: financial123
  JWT_SECRET: financial-hub-secret-key-must-be-at-least-256-bits-long-for-hs256
  AWS_ACCESS_KEY_ID: CHANGE_ME
  AWS_SECRET_ACCESS_KEY: CHANGE_ME
