sonar.projectKey=emanueleborges_financial
sonar.organization=emanueleborges
sonar.projectName=Financial Hub
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,services/notification-service/src/main/java,web-angular/src
sonar.tests=backend/src/test/java,services/notification-service/src/test/java
sonar.java.binaries=backend/target/classes,services/notification-service/target/classes
sonar.java.source=17
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml,services/notification-service/target/site/jacoco/jacoco.xml
sonar.exclusions=**/*Application.java,**/*Config.java,**/generated/**
