CREATE TABLE NOTIFICATIONS (
    ID VARCHAR2(36) PRIMARY KEY,
    EVENT_ID VARCHAR2(64) NOT NULL,
    RECIPIENT_EMAIL VARCHAR2(255) NOT NULL,
    RECIPIENT_DOCUMENT VARCHAR2(14),
    MESSAGE VARCHAR2(1000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_NOTIF_EVENT_EMAIL UNIQUE (EVENT_ID, RECIPIENT_EMAIL)
);
